allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
overrides:
  '@sokol111/ecommerce-tenant-service-api': link:../ecommerce-tenant-service-api/gen/typescript
